
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python app.py"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres
    container_name: locall_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Manju123#
      POSTGRES_DB: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8889:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: gaureesanthosh@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Manju123#
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
