# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegister():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_register(self):
    self.driver.get("http://localhost:5000/")
    self.driver.set_window_size(812, 608)
    self.driver.find_element(By.LINK_TEXT, "LOGIN").click()
    self.driver.find_element(By.LINK_TEXT, "REGISTER HERE!").click()
    self.driver.find_element(By.NAME, "fullname").click()
    self.driver.find_element(By.NAME, "fullname").send_keys("Saba")
    self.driver.find_element(By.NAME, "username").send_keys("saba")
    self.driver.find_element(By.NAME, "email").send_keys("saba@gmail.com")
    self.driver.find_element(By.NAME, "phone").send_keys("6360223782")
    self.driver.find_element(By.NAME, "password").send_keys("123")
    self.driver.find_element(By.NAME, "confirm_password").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, ".two").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button > input").click()
  
