# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestService():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_service(self):
    self.driver.get("http://localhost:5000/")
    self.driver.set_window_size(815, 611)
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > input").send_keys("Priyanka ANand")
    self.driver.find_element(By.CSS_SELECTOR, ".form_container").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > input").send_keys("06360223782")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > input").send_keys("saba@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".message-box").click()
    self.driver.find_element(By.CSS_SELECTOR, ".message-box").send_keys("HOII")
    self.driver.find_element(By.CSS_SELECTOR, ".btn_box > button").click()
  
