# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBooking():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_booking(self):
    self.driver.get("http://localhost:5000/")
    self.driver.set_window_size(820, 616)
    self.driver.find_element(By.CSS_SELECTOR, ".s-3").click()
    self.driver.find_element(By.CSS_SELECTOR, ".overlay-content > a:nth-child(4)").click()
    self.driver.find_element(By.NAME, "fullname").click()
    self.driver.find_element(By.NAME, "fullname").send_keys("Priyanka")
    self.driver.find_element(By.NAME, "email").send_keys("priyanka.whee@gmail.com")
    self.driver.find_element(By.NAME, "phone").send_keys("6360223782")
    self.driver.find_element(By.NAME, "comments").click()
    self.driver.find_element(By.NAME, "comments").send_keys(":)")
    self.driver.find_element(By.NAME, "preferred_date").click()
    self.driver.find_element(By.NAME, "preferred_date").click()
    self.driver.find_element(By.NAME, "preferred_date").send_keys("2024-05-23")
  
